version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/container-restaurant-test/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationInstall:
    - location: stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user
  ValidateServer:
    - location: health.sh
      timeout: 60
      runas: ec2-user