name: CICD

on:
  push:
    branches: [ develop ]

jobs:
  cicd:
    name: CICD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Make for deploy directory
        run: mkdir -p deploy

      - name: Copy JAR file
        run: cp build/libs/*.jar deploy/

      - name: Make zip file
        run: zip -r deploy/container-restaurant.zip deploy/*

      # 여기서 부터는 CD 를 위한 AWS 관련 작업
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: >
          aws s3 cp
          --region ap-northeast-2
          ./deploy/container-restaurant.zip
          s3://container-restaurant-deploy/container-restaurant.zip
